/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SigninRouteImport } from './routes/signin'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as HowItWorksRouteImport } from './routes/how-it-works'
import { Route as FeaturesRouteImport } from './routes/features'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as BusinessRouteImport } from './routes/business'
import { Route as DashboardRouteImport } from './routes/_dashboard'
import { Route as SlugRouteImport } from './routes/$slug'
import { Route as IndexRouteImport } from './routes/index'
import { Route as USlugRouteImport } from './routes/u.$slug'
import { Route as BusinessDashboardRouteImport } from './routes/business.dashboard'
import { Route as DashboardSettingsRouteImport } from './routes/_dashboard.settings'
import { Route as DashboardProfileRouteImport } from './routes/_dashboard.profile'
import { Route as DashboardBillingRouteImport } from './routes/_dashboard.billing'
import { Route as BusinessDashboardIndexRouteImport } from './routes/business.dashboard.index'
import { Route as BusinessDashboardTeamRouteImport } from './routes/business.dashboard.team'
import { Route as BusinessDashboardRequestsRouteImport } from './routes/business.dashboard.requests'
import { Route as BusinessDashboardOfferRouteImport } from './routes/business.dashboard.offer'

const SigninRoute = SigninRouteImport.update({
  id: '/signin',
  path: '/signin',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const HowItWorksRoute = HowItWorksRouteImport.update({
  id: '/how-it-works',
  path: '/how-it-works',
  getParentRoute: () => rootRouteImport,
} as any)
const FeaturesRoute = FeaturesRouteImport.update({
  id: '/features',
  path: '/features',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const BusinessRoute = BusinessRouteImport.update({
  id: '/business',
  path: '/business',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/_dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const SlugRoute = SlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const USlugRoute = USlugRouteImport.update({
  id: '/u/$slug',
  path: '/u/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const BusinessDashboardRoute = BusinessDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => BusinessRoute,
} as any)
const DashboardSettingsRoute = DashboardSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardProfileRoute = DashboardProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardBillingRoute = DashboardBillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => DashboardRoute,
} as any)
const BusinessDashboardIndexRoute = BusinessDashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => BusinessDashboardRoute,
} as any)
const BusinessDashboardTeamRoute = BusinessDashboardTeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => BusinessDashboardRoute,
} as any)
const BusinessDashboardRequestsRoute =
  BusinessDashboardRequestsRouteImport.update({
    id: '/requests',
    path: '/requests',
    getParentRoute: () => BusinessDashboardRoute,
  } as any)
const BusinessDashboardOfferRoute = BusinessDashboardOfferRouteImport.update({
  id: '/offer',
  path: '/offer',
  getParentRoute: () => BusinessDashboardRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$slug': typeof SlugRoute
  '/business': typeof BusinessRouteWithChildren
  '/contact': typeof ContactRoute
  '/features': typeof FeaturesRoute
  '/how-it-works': typeof HowItWorksRoute
  '/pricing': typeof PricingRoute
  '/register': typeof RegisterRoute
  '/signin': typeof SigninRoute
  '/billing': typeof DashboardBillingRoute
  '/profile': typeof DashboardProfileRoute
  '/settings': typeof DashboardSettingsRoute
  '/business/dashboard': typeof BusinessDashboardRouteWithChildren
  '/u/$slug': typeof USlugRoute
  '/business/dashboard/offer': typeof BusinessDashboardOfferRoute
  '/business/dashboard/requests': typeof BusinessDashboardRequestsRoute
  '/business/dashboard/team': typeof BusinessDashboardTeamRoute
  '/business/dashboard/': typeof BusinessDashboardIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$slug': typeof SlugRoute
  '/business': typeof BusinessRouteWithChildren
  '/contact': typeof ContactRoute
  '/features': typeof FeaturesRoute
  '/how-it-works': typeof HowItWorksRoute
  '/pricing': typeof PricingRoute
  '/register': typeof RegisterRoute
  '/signin': typeof SigninRoute
  '/billing': typeof DashboardBillingRoute
  '/profile': typeof DashboardProfileRoute
  '/settings': typeof DashboardSettingsRoute
  '/u/$slug': typeof USlugRoute
  '/business/dashboard/offer': typeof BusinessDashboardOfferRoute
  '/business/dashboard/requests': typeof BusinessDashboardRequestsRoute
  '/business/dashboard/team': typeof BusinessDashboardTeamRoute
  '/business/dashboard': typeof BusinessDashboardIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$slug': typeof SlugRoute
  '/_dashboard': typeof DashboardRouteWithChildren
  '/business': typeof BusinessRouteWithChildren
  '/contact': typeof ContactRoute
  '/features': typeof FeaturesRoute
  '/how-it-works': typeof HowItWorksRoute
  '/pricing': typeof PricingRoute
  '/register': typeof RegisterRoute
  '/signin': typeof SigninRoute
  '/_dashboard/billing': typeof DashboardBillingRoute
  '/_dashboard/profile': typeof DashboardProfileRoute
  '/_dashboard/settings': typeof DashboardSettingsRoute
  '/business/dashboard': typeof BusinessDashboardRouteWithChildren
  '/u/$slug': typeof USlugRoute
  '/business/dashboard/offer': typeof BusinessDashboardOfferRoute
  '/business/dashboard/requests': typeof BusinessDashboardRequestsRoute
  '/business/dashboard/team': typeof BusinessDashboardTeamRoute
  '/business/dashboard/': typeof BusinessDashboardIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$slug'
    | '/business'
    | '/contact'
    | '/features'
    | '/how-it-works'
    | '/pricing'
    | '/register'
    | '/signin'
    | '/billing'
    | '/profile'
    | '/settings'
    | '/business/dashboard'
    | '/u/$slug'
    | '/business/dashboard/offer'
    | '/business/dashboard/requests'
    | '/business/dashboard/team'
    | '/business/dashboard/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$slug'
    | '/business'
    | '/contact'
    | '/features'
    | '/how-it-works'
    | '/pricing'
    | '/register'
    | '/signin'
    | '/billing'
    | '/profile'
    | '/settings'
    | '/u/$slug'
    | '/business/dashboard/offer'
    | '/business/dashboard/requests'
    | '/business/dashboard/team'
    | '/business/dashboard'
  id:
    | '__root__'
    | '/'
    | '/$slug'
    | '/_dashboard'
    | '/business'
    | '/contact'
    | '/features'
    | '/how-it-works'
    | '/pricing'
    | '/register'
    | '/signin'
    | '/_dashboard/billing'
    | '/_dashboard/profile'
    | '/_dashboard/settings'
    | '/business/dashboard'
    | '/u/$slug'
    | '/business/dashboard/offer'
    | '/business/dashboard/requests'
    | '/business/dashboard/team'
    | '/business/dashboard/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SlugRoute: typeof SlugRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  BusinessRoute: typeof BusinessRouteWithChildren
  ContactRoute: typeof ContactRoute
  FeaturesRoute: typeof FeaturesRoute
  HowItWorksRoute: typeof HowItWorksRoute
  PricingRoute: typeof PricingRoute
  RegisterRoute: typeof RegisterRoute
  SigninRoute: typeof SigninRoute
  USlugRoute: typeof USlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signin': {
      id: '/signin'
      path: '/signin'
      fullPath: '/signin'
      preLoaderRoute: typeof SigninRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/how-it-works': {
      id: '/how-it-works'
      path: '/how-it-works'
      fullPath: '/how-it-works'
      preLoaderRoute: typeof HowItWorksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/features': {
      id: '/features'
      path: '/features'
      fullPath: '/features'
      preLoaderRoute: typeof FeaturesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/business': {
      id: '/business'
      path: '/business'
      fullPath: '/business'
      preLoaderRoute: typeof BusinessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_dashboard': {
      id: '/_dashboard'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$slug': {
      id: '/$slug'
      path: '/$slug'
      fullPath: '/$slug'
      preLoaderRoute: typeof SlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/u/$slug': {
      id: '/u/$slug'
      path: '/u/$slug'
      fullPath: '/u/$slug'
      preLoaderRoute: typeof USlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/business/dashboard': {
      id: '/business/dashboard'
      path: '/dashboard'
      fullPath: '/business/dashboard'
      preLoaderRoute: typeof BusinessDashboardRouteImport
      parentRoute: typeof BusinessRoute
    }
    '/_dashboard/settings': {
      id: '/_dashboard/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof DashboardSettingsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/profile': {
      id: '/_dashboard/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof DashboardProfileRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/billing': {
      id: '/_dashboard/billing'
      path: '/billing'
      fullPath: '/billing'
      preLoaderRoute: typeof DashboardBillingRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/business/dashboard/': {
      id: '/business/dashboard/'
      path: '/'
      fullPath: '/business/dashboard/'
      preLoaderRoute: typeof BusinessDashboardIndexRouteImport
      parentRoute: typeof BusinessDashboardRoute
    }
    '/business/dashboard/team': {
      id: '/business/dashboard/team'
      path: '/team'
      fullPath: '/business/dashboard/team'
      preLoaderRoute: typeof BusinessDashboardTeamRouteImport
      parentRoute: typeof BusinessDashboardRoute
    }
    '/business/dashboard/requests': {
      id: '/business/dashboard/requests'
      path: '/requests'
      fullPath: '/business/dashboard/requests'
      preLoaderRoute: typeof BusinessDashboardRequestsRouteImport
      parentRoute: typeof BusinessDashboardRoute
    }
    '/business/dashboard/offer': {
      id: '/business/dashboard/offer'
      path: '/offer'
      fullPath: '/business/dashboard/offer'
      preLoaderRoute: typeof BusinessDashboardOfferRouteImport
      parentRoute: typeof BusinessDashboardRoute
    }
  }
}

interface DashboardRouteChildren {
  DashboardBillingRoute: typeof DashboardBillingRoute
  DashboardProfileRoute: typeof DashboardProfileRoute
  DashboardSettingsRoute: typeof DashboardSettingsRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardBillingRoute: DashboardBillingRoute,
  DashboardProfileRoute: DashboardProfileRoute,
  DashboardSettingsRoute: DashboardSettingsRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

interface BusinessDashboardRouteChildren {
  BusinessDashboardOfferRoute: typeof BusinessDashboardOfferRoute
  BusinessDashboardRequestsRoute: typeof BusinessDashboardRequestsRoute
  BusinessDashboardTeamRoute: typeof BusinessDashboardTeamRoute
  BusinessDashboardIndexRoute: typeof BusinessDashboardIndexRoute
}

const BusinessDashboardRouteChildren: BusinessDashboardRouteChildren = {
  BusinessDashboardOfferRoute: BusinessDashboardOfferRoute,
  BusinessDashboardRequestsRoute: BusinessDashboardRequestsRoute,
  BusinessDashboardTeamRoute: BusinessDashboardTeamRoute,
  BusinessDashboardIndexRoute: BusinessDashboardIndexRoute,
}

const BusinessDashboardRouteWithChildren =
  BusinessDashboardRoute._addFileChildren(BusinessDashboardRouteChildren)

interface BusinessRouteChildren {
  BusinessDashboardRoute: typeof BusinessDashboardRouteWithChildren
}

const BusinessRouteChildren: BusinessRouteChildren = {
  BusinessDashboardRoute: BusinessDashboardRouteWithChildren,
}

const BusinessRouteWithChildren = BusinessRoute._addFileChildren(
  BusinessRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SlugRoute: SlugRoute,
  DashboardRoute: DashboardRouteWithChildren,
  BusinessRoute: BusinessRouteWithChildren,
  ContactRoute: ContactRoute,
  FeaturesRoute: FeaturesRoute,
  HowItWorksRoute: HowItWorksRoute,
  PricingRoute: PricingRoute,
  RegisterRoute: RegisterRoute,
  SigninRoute: SigninRoute,
  USlugRoute: USlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
